### ISSUE TITLE
VeloSim preprint

### ISSUE THREAD

**Issue by rcannood** [PeterZZQ/VeloSim#1]
Hello all! 

First of all, congrats on the publication of your VeloSim preprint. As the author of dyngen, I thought it was an interesting read; you definitely bring up interesting points of dicussion. For example, the fact that VeloSim includes a two-state kinetic model, it's something we've been considering including in dyngen as well, but in the end thought it would change the expected behaviour of dyngen too much.

I don't want to go into the benefits or downsides of VeloSim vs. dyngen at this stage, but would like to briefly discuss a statement made about dyngen:
> Dyngen and SERGIO are able to simulate both spliced and unspliced mRNA counts of cells in a continuous dynamic process, but they each has its own limitations in practice. Dyngen provides predefined trajectory structure types in the package, such as bifurcating or cycle, but it is not flexible enough for more customized trajectory structure where user need to specify the exact developmental tree structure and the length of each branch.

While it is true that dyngen provides a lot of predefined trajectory structures ([documented here](https://github.com/dynverse/dyngen/blob/devel/vignettes/showcase_backbones.md)), users are also allowed to specify a custom trajectory topology ([documented here](https://github.com/dynverse/dyngen/blob/devel/vignettes/advanced_constructing_backbone.md)). 

In your next version of the preprint, could you have this statement changed?

Kind regards,
Robrecht

**Comment by xiuweiz** [comment]
Hi Robrecht,

Thank you very much for your valuable comment. Now that you have pointed out, we can see that the statement in the manuscript can be interpreted as that dyngen does not take customized trajectories at all. We will modify the statement so that it reflects the information you provided and submit an updated version within one or two weeks. 

Dyngen is a great tool and I particularly like the part that it uses GRNs to drive the trajectories. In fact, we have used it a lot in our projects, and as we were not sure how to specify certain things (for example, the number of cells on each branch in a tree structure) when using dyngen we developed VeloSim to use along with dyngen. It could be that something like what you shared in the advanced manual can allow us to do that, and we may reach out to you in the next few weeks if we don't figure it out by ourselves. 

Best,
Xiuwei
